### ISSUE TITLE
Error in Linux

### ISSUE THREAD

**Issue by HotDrive69** [Bloodreaver/Archon#5]
When running Archon in Linux I get "error while loading shared libraries: libssl.so.1.1:" error.

**Comment by bu11ettrain** [comment]
You need install openssl 1.1.0

**Comment by HotDrive69** [comment]
I have openssl 1.1.0

**Comment by bu11ettrain** [comment]
sudo find / -iname 'libssl*'

**Comment by HotDrive69** [comment]
/usr/share/doc/libssl-doc
/usr/share/doc/libssl-dev
/usr/share/doc/libssl1.0.0
/usr/lib/firefox/libssl3.so
/usr/lib/x86_64-linux-gnu/libssl3.so
/usr/lib/x86_64-linux-gnu/libssl.a
/usr/lib/x86_64-linux-gnu/pkgconfig/libssl.pc
/usr/lib/x86_64-linux-gnu/libssl.so
/usr/lib/plexmediaserver/libssl.so.1.0.0
/usr/local/lib/libssl.so.1.1
/usr/local/lib/libssl.a
/usr/local/lib/pkgconfig/libssl.pc
/usr/local/lib/libssl.so
/var/lib/dpkg/info/libssl1.0.0:amd64.postrm
/var/lib/dpkg/info/libssl1.0.0:i386.list
/var/lib/dpkg/info/libssl-dev:amd64.list
/var/lib/dpkg/info/libssl1.0.0:amd64.symbols
/var/lib/dpkg/info/libssl-doc.list
/var/lib/dpkg/info/libssl1.0.0:amd64.postinst
/var/lib/dpkg/info/libssl1.0.0:i386.triggers
/var/lib/dpkg/info/libssl-dev:amd64.md5sums
/var/lib/dpkg/info/libssl1.0.0:i386.postinst
/var/lib/dpkg/info/libssl1.0.0:amd64.templates
/var/lib/dpkg/info/libssl1.0.0:i386.md5sums
/var/lib/dpkg/info/libssl1.0.0:amd64.md5sums
/var/lib/dpkg/info/libssl1.0.0:i386.symbols
/var/lib/dpkg/info/libssl1.0.0:amd64.list
/var/lib/dpkg/info/libssl1.0.0:i386.postrm
/var/lib/dpkg/info/libssl1.0.0:i386.shlibs
/var/lib/dpkg/info/libssl1.0.0:amd64.shlibs
/var/lib/dpkg/info/libssl1.0.0:amd64.triggers
/var/lib/dpkg/info/libssl-doc.md5sums
/var/lib/dpkg/info/libssl1.0.0:i386.templates
/var/cache/apt/archives/libssl1.0.0_1.0.2g-1ubuntu4.15_amd64.deb
/var/cache/apt/archives/libssl1.0.0_1.0.2g-1ubuntu4.15_i386.deb
/lib/x86_64-linux-gnu/libssl.so.1.0.0
/lib/i386-linux-gnu/libssl.so.1.0.0
find: "/run/user/1000/gvfs": Permissão negada
/home/hotdrive/cm_old/lib/libssl.so.1.0.0
/home/hotdrive/cm_old/lib/libssl.so
/home/hotdrive/tmp/openssl-1.1.0k/libssl.pc
/home/hotdrive/tmp/openssl-1.1.0k/util/libssl.num
/home/hotdrive/tmp/openssl-1.1.0k/libssl.so.1.1
/home/hotdrive/tmp/openssl-1.1.0k/libssl.a
/home/hotdrive/tmp/openssl-1.1.0k/libssl.so
/home/hotdrive/cm/lib/libssl.so.1.0.0
/home/hotdrive/cm/lib/libssl.so

**Comment by HotDrive69** [comment]
Output of -> openssl version -a
OpenSSL 1.1.0k  28 May 2019
built on: reproducible build, date unspecified
platform: linux-x86_64
options:  bn(64,64) rc4(16x,int) des(int) idea(int) blowfish(ptr) 
compiler: gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-1.1\""  -Wa,--noexecstack
OPENSSLDIR: "/usr/local/ssl"
ENGINESDIR: "/usr/local/lib/engines-1.1"

**Comment by HotDrive69** [comment]
GOT IT! I missed the "ldconfig" part, to update paths. I think its running now.
Thanks for the help.
